# Generated by Django 5.2.7 on 2025-11-22 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main_App', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='players',
            name='email',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
    ]
